### ISSUE TITLE
Mongo connector stops pushing data

### ISSUE THREAD

**Issue by Thunkar** [mongodb-labs/mongo-connector#471]
I'm running mongo-connector inside a docker container with elasticsearch 2 and after a random amount of time it displays the following exception:

![Exception](https://cloud.githubusercontent.com/assets/5404052/16006588/313d1a54-316e-11e6-98ec-a5bb5d146f66.png)
 
After this, no new data is indexed in Elasticsearch. Sometimes deleting the oplog.timestamp file solves the problem (it is always empty, though), sometimes not. My docker-compose file is the following:

```
version: "2"
services:
    elasticsearch:
        image: elasticsearch:latest
        container_name: elasticsearch
        ports:
            - "9200:9200"
        volumes:
            - ./elasticsearch/config:/usr/share/elasticsearch/config
            - ./elasticsearch/data:/usr/share/elasticsearch/data 
    mongo-connector:
        image: mongo-connector:latest
        build:
            context: ./mongo-connector
            dockerfile: mongo-connector.docker
        container_name: mongo-connector
        command: mongo-connector -c /etc/mongo-connector/config.json 
        restart: always
        volumes:
            - ./mongo-connector/config.json:/etc/mongo-connector/config.json
            - ./mongo-connector/logs:/var/log/mongo-connector
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
    logstash:
        image: logstash:latest
        container_name: logstash
        command: logstash -f /etc/logstash/conf.d/logstash.conf
        volumes:
            - ./logstash/config:/etc/logstash/conf.d
            - /var/log/nginx:/var/log/nginx
        ports:
            - "5000:5000"
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
    kibana:
        image: kibana-w-plugins:latest
        build:
            context: ./kibana
            dockerfile: kibana-w-plugins.docker
        container_name: kibana
        ports:
            - "5601:5601"
        volumes:
            - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
```

And my mongo-connector config is this:

```
{
    "mainAddress": "***",
    "oplogFile": "/var/log/mongo-connector/oplog.timestamp",
    "noDump": false,
    "batchSize": 100,
    "verbosity": 1,
    "continueOnError": false,

    "logging": {
        "type": "file",
        "filename": "/var/log/mongo-connector/mongo-connector.log"
    },

    "authentication": {
        "adminUsername": "***",
        "password": "***"
    },

    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "http://elasticsearch:9200"
        }
    ]
}
```

As you can see, the oplog file resides on the host and it is mounted into the container, which in turn can use it and write to it as the folder has 775 permissions. Any help would be appreciated.
